Add stripping of trailing whitespace to pre-commit
radis/radis pull request #142
Opened 2020-12-05 21:37 UTC by suzil

### Description

Add a pre-commit hook to strip trailing whitespace. It's commit noise, and this pre-commit hook will keep it consistent by stripping it always.

2020-12-05 21:48 UTC, suzil commented
I'm intrigued as to why CI fails from stripping whitespace 😁

2020-12-05 22:51 UTC, erwanp commented
The `.spec` files are how we store our Spectrum objects with metadata. They're either renamed .json, or compressed as binary. Looks like pre-commit [modified the binaries](https://github.com/radis/radis/pull/142/files?file-filters%5B%5D=.spec).

2020-12-06 02:09 UTC, suzil commented
Excluded those files:

```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
                ^.+.spec|
                ^.+.dat
            )
```

2020-12-06 12:09 UTC, erwanp requested changes
suggested another change, otherwise we're good to go !

2020-12-06 12:09 UTC, erwanp commented on .pre-commit-config.yaml
> +                ^.+.dat
Hello ! I also excluded the .levels files, which are some other plain text input files. 

```suggestion
                ^.+.dat|
                ^.+.levels
```

2020-12-06 14:57 UTC, suzil commented
```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
                ^.+\.spec|
                ^.+\.dat|
                ^.+\.levels
            )
```
- Added `*.levels`
- Fixed regex to escape the period before the file extension

2020-12-06 15:11 UTC, merged