Faster rejection of irrelevant files
radis/radis pull request #185
Opened 2021-01-14 15:03 UTC by CorentinGrimaldi

### Description

This pull request is to address #131 with a better file check relevancy by storing wmin and wmax in the cache file metadata. 
So we do not need to load all the cached file for nothing. Only the metadata are loaded and if the file is relevant for the calcul the file is loaded.
This allow for a much faster rejection of irrelevant file and speeding up the loading of large database such as CDSD-4000. Change from about 1s by file to 0.01s (approximately).

Fixes #<Issue Number>

2021-01-14 16:10 UTC, erwanp requested changes

2021-01-14 16:10 UTC, erwanp commented on radis/lbl/loader.py
> +                        if df == "IrrelevantFile":
Could be replaced by a larger

```
try:
    df = .... 
except IrrelevantFileError:
    if db_use_cached=='force':
        raise
     else:
        continue
``` 

`df` is not rewritten.

2021-01-16 23:22 UTC, erwanp commented
Will help #166 too

2021-01-29 12:03 UTC, erwanp requested changes

2021-01-29 12:03 UTC, erwanp commented on radis/io/cdsd.py
> +    wavenum_min=0.0,
It's not straightforward what wavenum_min and max do here. Can you : 
- change the name to something explicit ? Ex : `load_only_wavenum_above=` ,  `load_only_wavenum_below=`? 
- add the names in the docstrings under Other Parameters with a shortdescription. In the docs, if needed, you can also refer to other functions like load_h5_cache_file using ``` :py:func`~radis.misc.cache_files` ```

2021-01-29 14:46 UTC, erwanp commented on radis/lbl/loader.py
> +                            continue
maybe add a low-level print here ? (if verbose==2 or 3  for instance ? )

2021-01-29 14:55 UTC, CorentinGrimaldi commented on radis/io/cdsd.py
> +            raise err
Ah yes, no need to do that, in my mind it was a way to transmit the warning to the upper function.
Will remove it.

2021-01-29 15:01 UTC, CorentinGrimaldi commented on radis/io/cdsd.py
> +            raise err
As in radis/io/hitran.py

2021-01-31 18:42 UTC, erwanp approved these changes

2021-01-31 18:50 UTC, erwanp commented
Very nice, merging ! 

@BlehMaks have a look at the PR, it can be useful to you : you may need to regenerate your cache files, but then it will make the whole loading process super fast even with the whole CDSD-4000 Database !

2021-01-31 18:50 UTC, merged