Code readability
radis/radis pull request #235
Opened 2021-04-11 17:19 UTC by madhavshah49

### Description

This pull request is to address ...

Fixes #<Issue Number>

2021-04-12 12:37 UTC, erwanp commented on docs/spectrum/spectrum.rst
> +Plotline survey
```suggestion
Plotline survey
```

not sure of this one !

2021-04-12 12:39 UTC, erwanp requested changes

2021-04-12 12:39 UTC, erwanp commented on docs/spectrum/spectrum.rst
> +a new convolved spectral quantity is created. The unit of the convolved quantity may be different,
```suggestion
a new convolved spectral array is created. The unit of the convolved spectral array may be different,
```

the name is being changed in #236

2021-04-12 12:39 UTC, erwanp commented on docs/spectrum/spectrum.rst
>  -------------------
```suggestion
------------------
```

alignment

2021-04-15 09:13 UTC, erwanp commented
@madhavshah49 have a look, couple minor change requests + one conflict

2021-04-30 14:48 UTC, madhavshah49 commented
@erwanp hey I've done the minor changes sorry did not create the pull request yet and the conflict you want me to add something to the file or just redraft it as it was earlier

2021-04-30 14:49 UTC, madhavshah49 commented
@erwanp hey I've done the minor changes sorry it took a while and did not create the pull request yet, also in the conflict do you want me to add something to the file or just redraft it as it was earlier

2021-04-30 15:35 UTC, madhavshah49 commented
@erwanp hey I've done the minor changes sorry it took a while, also in the conflict do you want me to add something additional to the file or just redraft it as it was earlier

2021-04-30 16:48 UTC, erwanp commented
No worries. You can fix the conflict by picking the option that uses "array"  not "quantity"

2021-05-01 09:18 UTC, madhavshah49 commented
@erwanp Ready to merge?

2021-05-01 09:22 UTC, erwanp commented
Can you fix the conflict?

2021-05-01 10:39 UTC, erwanp requested changes
Fix format of titles, and make sure we use "line survey" and not "plotline survey" (@madhavshah49  you can accept everything from the Web interface with Batch commits !)

2021-05-01 10:39 UTC, erwanp commented on docs/spectrum/spectrum.rst
>  ====================================
```suggestion
How to access Spectrum properties?
==================================
```

2021-05-01 10:39 UTC, erwanp commented on docs/spectrum/spectrum.rst
>  ---------------------------
```suggestion
Get wavelength/wavenumber
-------------------------
```

2021-05-01 10:39 UTC, erwanp commented on docs/spectrum/spectrum.rst
> +Plotline survey
```suggestion
Plot Line survey
```

2021-05-29 15:14 UTC, erwanp approved these changes

2021-05-29 16:12 UTC, merged