Changed 'Spectral Quantity' to 'Spectral Array' at every occurrence
radis/radis pull request #236
Opened 2021-04-11 18:40 UTC by AlphaVictorDelta

### Description

docs: rename "spectral quantities" (radiance, transmittance, abscoeff, etc.) to "spectral arrays" consistently throughout the code

Fixes part 2 of  issue #77

2021-04-11 18:43 UTC, AlphaVictorDelta commented
@minouHub @erwanp  I have deleted the old pull request because I realized there were many mistakes in the previous pull request. To avoid confusion, I started the whole thing afresh. Could you please take a look? Thank you for your patience.

2021-04-12 16:59 UTC, erwanp requested changes
minor changes so that Sphinx properly generates the documentation titles without warnings

2021-04-12 16:59 UTC, erwanp commented on docs/spectrum/spectrum.rst
>  ===================
```suggestion
Spectral Arrays
===============
```

2021-04-12 16:59 UTC, erwanp commented on docs/spectrum/spectrum.rst
>  --------------------------
```suggestion
----------------------
```

2021-04-12 16:59 UTC, erwanp commented on docs/spectrum/spectrum.rst
>  -----------------------
```suggestion
-------------------
```

2021-04-12 16:59 UTC, erwanp commented on docs/spectrum/spectrum.rst
>  ------------------------
```suggestion
--------------------
```

2021-04-13 15:23 UTC, AlphaVictorDelta commented
@erwanp erwan I made the changes you requested but now the build is failing.

2021-04-13 15:33 UTC, erwanp approved these changes

2021-04-13 15:36 UTC, erwanp commented
Test shows you need to run `black` on `radis/radis/docs/conf.py` . Seems to be missing a comma "," [L68](https://github.com/radis/radis/pull/236/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3L62), too.

2021-04-13 17:05 UTC, erwanp approved these changes

2021-04-13 17:07 UTC, merged