add: plot_linestrength example
radis/radis pull request #293
Opened 2021-06-22 14:02 UTC by gagan-aryan

### Description

This pull request iadds the example to plot linestrengths as a bar plot in the waverange.

2021-06-22 14:55 UTC, erwanp commented
Super nice ! Does it correctly build the docs locally ?

One issue I can see about adding this in the main Examples : it uses CH4 ; which is very long to download and process. The examples will be re-computed for every change to the `develop` branch, so we want to limit data traffic. What about using CO for the online version ?

2021-06-22 17:03 UTC, gagan-aryan commented
@erwanp I have replaced it with CO and yes the docs pass locally.

2021-06-22 18:07 UTC, erwanp requested changes

2021-06-22 18:07 UTC, erwanp commented on examples/plot_linestrengths.py
> +"""
We can use these examples to give information about what's done in the code (good for future spectroscopy tutorials !)

```suggestion
Similar functions are used directly at the hearth of RADIS's SpectrumFactory in the :py:meth:`~radis.lbl.BaseFactory.calc_linestrength_eq` and :py:meth:`~radis.lbl.BaseFactory.calc_linestrength_noneq` methods
"""
```

I also suggest that you : 
- borrow the equation and link to the references of BaseFactory.calc_linestrength_eq docstrings, and add it here. Will look very nice !
- mention this example in BaseFactory.calc_linestrength_eq docstring, by adding 
```
.. minigallery:: radis.lbl.base.BaseFactory.calc_linestrength_eq
```
- make BaseFactory._calc_linestrength_noneq a public method by renaming it BaseFactory.calc_linestrength_noneq

2021-06-22 18:07 UTC, erwanp commented on examples/plot_linestrengths.py
> +    Tgas = 300
Scaling from 296 to 300 K doesn't sound like a lot of changes. What about scaling up to, let's say, 450 K ?

2021-06-23 07:46 UTC, gagan-aryan commented on examples/plot_linestrengths.py
> +    df["Qgas"] = Qgas_arr.take(df.iso)
So we will be able to merge this once we the new approach in merged to the main code ?

2021-06-23 09:48 UTC, erwanp commented on examples/plot_linestrengths.py
> +    df["Qgas"] = Qgas_arr.take(df.iso)
Yes. We can even add your example before the main code is upgraded;  but the example should use the map(dict) approach not to have to modify it afterwards (also, it's faster as you've shown !)

2021-06-24 17:35 UTC, erwanp commented on examples/plot_linestrengths.py
>          if iso in iso_set:
@gagan-aryan one more comment : why do you need to create iso_arr ? Can't we just do `for iso in iso_set` ?

2021-06-24 17:36 UTC, erwanp approved these changes

2021-06-24 18:31 UTC, erwanp approved these changes

2021-06-24 18:32 UTC, merged