Add some improvements in fetch_*() documentations
radis/radis pull request #442
Opened 2022-04-05 16:11 UTC by TranHuuNhatHuy

### Description

This pull request is to solve issues suggested by @erwanp 's comment [here](https://github.com/radis/radis/issues/77#issuecomment-1087403583)

As [this gallery example](https://radis.readthedocs.io/en/latest/auto_examples/plot_hitemp_OH_database.html#sphx-glr-auto-examples-plot-hitemp-oh-database-py) features both HITRAN and HITEMP fetching, I add it into gallery example sessions of both `fetch_hitran()` and `fetch_hitemp()`. When a gallery example specifically for HITRAN is available, we can use it for HITRAN one.

2022-04-05 16:41 UTC, erwanp requested changes
You may need to add it in fetch_exomol() too

2022-04-06 01:56 UTC, TranHuuNhatHuy commented
> You may need to add the gallery reference in in fetch_exomol() too

@erwanp I noticed that currently in [fetch_exomol() docs](https://radis.readthedocs.io/en/latest/source/radis.io.exomol.html#radis.io.exomol.fetch_exomol) there are two gallery references already: 
![image](https://user-images.githubusercontent.com/29034232/161879594-a13acf43-1be8-466d-b0f2-8e089829e8f0.png)
(are gallery example and gallery reference the same, or am I misunderstanding something? My understanding comes from #136 so if I get something wrong please enlighten me)

2022-04-06 06:43 UTC, erwanp approved these changes

2022-04-06 06:44 UTC, erwanp commented
Indeed they're already here. Thanks for checking. Merging!

2022-04-06 06:44 UTC, merged