Implement astropy unit conversion to rescale_path_length()
radis/radis pull request #445
Opened 2022-04-06 12:38 UTC by TranHuuNhatHuy

### Description

This pull request is to address #444. Now we can use astropy units for the input arguments of `rescale_path_length()`.

Beside, currently on the RADIS documentation, `rescale_path_length()` has 2 references:

1. [radis.Spectrum.rescale_path_length](https://radis.readthedocs.io/en/latest/source/radis.html#radis.Spectrum.rescale_path_length)
2. [radis.Spectrum.rescale.rescale_path_length](https://radis.readthedocs.io/en/latest/source/radis.spectrum.rescale.html#radis.spectrum.rescale.rescale_path_length)

For [1]:

- @erwanp 's [syntax](https://github.com/radis/radis/issues/444#issue-1193462213) is added in the Examples section.
- I also notice that the gallery example for [1] does not show up on documentation. Currently the referring syntax is `.. minigallery:: radis.Spectrum.rescale_path_length`.
- Link for the source is currently not working. You can see it [here](https://radis.readthedocs.io/en/latest/source/radis.html#radis.Spectrum.rescale_path_length).

For [2], it's just kinda empty here.

2022-04-07 09:59 UTC, erwanp commented
Nice ! I think it should be _radis.**spectrum**.Spectrum.rescale_path_length_

there is a script in [doc/gendocs.sh](https://github.com/radis/radis/blob/develop/docs/gendocs.sh) that allows you to generate docs locally; helps the debugging. You may need to install the [doc specific requirements](https://github.com/radis/radis/blob/develop/docs/requirements.txt)

2022-04-07 10:04 UTC, erwanp commented
What we'll need before merging is to add **tests**.

There is a [test_rescale.py](https://github.com/radis/radis/blob/develop/radis/test/spectrum/test_rescale.py) file. You can add a new function there, testing the units. 

You can use a precomputed spectrum such as
```
s = load_spec(getTestFile("CO_Tgas1500K_mole_fraction0.01.spec"), binary=True)
```

and you could, for instance, compare the `absorbance`  (in absorption spectroscopy, the absorbance is A = k * L  where k is the absorption coefficient, L the length ; so absorbance should have changed when you rescaled the spectra )  of a a spectrum rescaled with astropy units (e.g `1 * u.m` ) and with default units (`100 # cm` )

2022-04-07 17:19 UTC, erwanp requested changes

2022-04-07 17:19 UTC, erwanp commented on radis/test/spectrum/test_rescale.py
> +    assert not np.array_equal(A0, A_km)
good idea to ensure this ! 👍

2022-04-07 22:03 UTC, TranHuuNhatHuy commented
@erwanp thank you for the reviews. Last commit features two changes according to your suggestions:

1. Fetch `absorbance` directly by using `s.get("absorbance", wunit='cm-1')`. I believe this is better than fetching `k` and `L` then calculate the absorbance `A = k * L`, in terms of computational performance and the sake of clean code.
2. Add third assertion of comparing the two `path_length` of 100000 cm and 1 u.km to make sure the astropy unit works fine. Although I doubt it is necessary if the two absorbances are already equal, I think with this we can check if something is wrong with the astropy units in the future (extremely unlikely thou).

2022-04-08 07:00 UTC, erwanp approved these changes

2022-04-08 07:01 UTC, erwanp commented
Excellent, merging!

2022-04-08 07:01 UTC, merged

2022-10-28 22:40 UTC, anandxkumar commented
Fixes #444