Fixes Issue#443
radis/radis pull request #447
Opened 2022-04-11 20:11 UTC by Supriya1702

### Description

This PR does the following:
- If `truncation=None` for `broadening_method='voigt'` for `optimization='simple' or 'min-RMS` method it raises NotImplementedError
- If `truncation` is negative it raises value error
- Allows computation for `broadening_method == "voigt"` and `truncation == None` for `optimization=None`

Fixes #443

2022-04-11 21:19 UTC, anandxkumar commented
Tested for different cases, works fine on my end, Good job! 
@erwanp should `truncation=None` work for `optimization=None` for `broadening_method='voigt'`?

2022-04-12 07:11 UTC, erwanp requested changes
Hello, good work! 

1. are you sure optimization=None is implemented?

2. We'd need a quick test, for instance one making sure an error is raised if negative truncation is given, and one making sure truncation=None does what we want. If you need help implementing tests please reach out on Slack

2022-04-12 07:11 UTC, erwanp commented on radis/lbl/factory.py
> +                "Lineshape truncation must be > 0. If you want no truncation (compute lineshape on the full spectral range), use `truncation=None`"
Can you also add :

"Note (advanced) : no truncation is not physically more accurate. Most molecules exhibit a sub-lorentzian behavior far from the line centers. A truncation at around 40-50 cm-1 is a good choice"

2022-04-12 18:57 UTC, Supriya1702 commented
Hello @erwanp, I added test for checking negative truncation and `truncation==None`. I found that `truncation=None` works for `broadening_method='voigt'` for `optimization=None` but gives error when used `fft`. Oppositely in `optimization='simple`, `truncation=None` works for `fft` but fails for `voigt`, so I added the tests accordingly

2022-04-12 19:54 UTC, erwanp approved these changes

2022-04-12 19:55 UTC, merged