Updated references.rst
radis/radis pull request #453
Opened 2022-04-15 09:33 UTC by sonikarajesh

Added links to Tutorials (radis/spectro101)

2022-04-15 09:44 UTC, erwanp requested changes

2022-04-15 09:44 UTC, erwanp commented on docs/references/references.rst
> +=============
```suggestion
Spectroscopy Tutorials
=====================
```

2022-04-15 09:52 UTC, erwanp commented on docs/references/references.rst
> +=============
@sonikarajesh you can commit directly from the web interface

2022-04-15 10:06 UTC, erwanp commented
Btw, RADIS enforces code linting ; here the test failed (see Checks)

Help on how to lint : https://radis.readthedocs.io/en/latest/dev/developer.html#code-linting

2022-04-15 20:32 UTC, erwanp commented
Can you check the linting errors?

2022-05-07 11:17 UTC, erwanp commented
@sonikarajesh gentle reminder as we need to fix linting errors to merge

2022-05-09 19:40 UTC, sonikarajesh commented
> @sonikarajesh gentle reminder as we need to fix linting errors to merge 
could you try merging?

2022-05-16 08:13 UTC, merged