Install command
radis/radis pull request #560
Opened 2023-04-03 23:10 UTC by menasrac

### Description

This pull request is to precise the specific command to install Radis depending on the plateform.

2023-04-04 07:04 UTC, minouHub commented on radis/lbl/factory.py
> +    kind : str, optional
we usually employ the keyword 'var' for variable

2023-04-04 07:06 UTC, minouHub commented on README.rst
> +Depending on your platform you should write
you *may* write. There are so many options. For dev, 'pip install -e .' is useful to also install dependencies

2023-04-04 07:06 UTC, minouHub commented
added a few comments. Good to go otherwise

2023-04-04 07:13 UTC, erwanp requested changes

2023-04-04 07:13 UTC, erwanp commented on README.rst
> +pip install radis
All 3 work in every OS. Let's keep it simple

2023-05-07 15:45 UTC, minouHub commented
@menasrac please implement the wording change that I suggested + revert the install instructions to the original as suggested by Erwan

2023-05-08 16:48 UTC, minouHub approved these changes

2023-05-19 10:23 UTC, merged