Kurucz clean new
radis/radis pull request #579
Opened 2023-07-05 10:27 UTC by menasrac

### Description

Cherry picked the right commit from the previous Kurucz PR.

2023-07-06 08:16 UTC, minouHub commented
Good job on making a cleaner version of PR #577. You also test that the code is running, that's essential. A missing essential test is to test the physics! I suggest that you find a simulation done by someone else as a reference, probably in one of the papers published by the Kurucz database, or on their website. 
I also could not find how you manage the broadening of the lines (Van der Waals, Doppler, Natural, Stark ...). We can talk about the physics outside of this PR if you want.

List of remaining things to do (potentially updated later)

**Physics tests**
- [ ] Compare a reference spectrum (downloaded or digitized from the literature) to your simulation 
- [ ] Compare a spectral value with a reference, e.g. integrated radiance, pic emission/absorption, linewidth

**Broadening**
- [ ] Which types of broadening are included? How do you manage them as a user?

**Spectrum class**
- [ ] You should use the spectrum class when you generate a spectrum.

2023-07-06 08:17 UTC, minouHub requested changes

2023-07-06 08:17 UTC, minouHub commented on radis/api/kuruczapi.py
> +    def plot_spectrum(self, data, populations, temperature):
[major] You should use the spectrum class of RADIS, with the method `s.plot()`

2023-07-23 20:35 UTC, erwanp requested changes
See changes, major request is that we need to inherit from a common API

2023-07-23 20:35 UTC, erwanp commented on pfdat.txt
what is this file and what is it doing at the root level ?

2023-07-23 20:35 UTC, erwanp commented on radis/api/kuruczapi.py
> +    def air_to_vac(self, wlair):
indeed

2023-07-23 20:35 UTC, erwanp commented on radis/api/kuruczapi.py
> +            gamvdW[i] = float(line[92:98])
There are usually much faster ways to parse a file than enumerate through all lines. 

See how we do in the HITRAN parser

2023-07-23 20:35 UTC, erwanp commented on radis/api/kuruczapi.py
> +        adata = pkgutil.get_data("exojax", "data/atom/atomic.txt")
@menasrac is this still exojax code ??

2023-07-23 20:35 UTC, erwanp commented on radis/api/kuruczapi.py
> +The AdBKurucz class below is inspired by an Exojax class developed by Hiroyuki Tako ISHIKAWA.
Add references and links to Exojax

2023-07-23 20:35 UTC, erwanp commented on radis/api/kuruczapi.py
> +            "exojax", "data/atom/NIST_Atomic_Ionization_Energies.txt"
same

2023-07-23 20:35 UTC, erwanp commented on radis/api/kuruczapi.py
> +class AdBKurucz:
MAJOR COMMENT. 
You should be inheriting from Radis API main Databases classes ; if you're simply rewriting another parser on the side it won't improve our goal towards a CommonAPI

2023-07-25 22:10 UTC, menasrac commented on pfdat.txt
The pfdat.txt file it is the barklem_collet_2016_pff.txt file from Exojax, it contains the partition function values for different atomic species at different temperatures. The columns correspond to specific temperatures, and the rows to specific atomic species. Since we noticed Exojax couldn't be installed on Windows because of a jaxlib issue, I had to moove the file locally. I did the same thing for the NIST_Atomic_Ionization_Energies.txt file which contains the ionization energies ( and will push the update soon).

2023-07-26 06:45 UTC, minouHub commented on pfdat.txt
You must move it with the other database files in `.radisdb\Kurucz` next to all the other databases

2023-08-14 17:15 UTC, erwanp commented
@menasrac you can close this PR if #601 is the newest

2023-08-15 11:09 UTC, closed without merging