Add Vulkan driver API
radis/radis pull request #624
Opened 2023-10-09 16:36 UTC by dcmvdbekerom

### Description

This pull request is to add Vulkan driver API. This adds support for all vendors (Nvidia/AMD/Intel/etc.) on all platforms (Windows/Linux/Mac).

Fixes #<Issue Number>

2023-10-15 14:23 UTC, dcmvdbekerom commented
Vulkan is working! It is still quite a bit slower, ~100ms (Vulkan) vs ~4ms (Cuda) on a Nvidia card, but I'm quite confident this can be solved through a better understanding of Vulkan and how to run pipelines efficiently.

Still lot's of open points, but the basic functionality is there.

You can change the GPU that's used by changing the `deviceID` keyword in line 108 of `radis.gpu.gpu.py` (changing the device will obviously be possible through keywords to spectrumfactory in the future).

2023-10-18 07:10 UTC, minouHub commented
Here is a test I tried. 
```python
from radis import SpectrumFactory, plot_diff

sf = SpectrumFactory(
    2150,
    2450,  # cm-1
    molecule="CO2",
    isotope="1,2,3",
    wstep=0.002,
)

sf.fetch_databank("hitemp")

T = 1500.0  # K
p = 1.0  # bar
x = 0.8
l = 0.2  # cm
w_slit = 0.5  # cm-1

# s_cpu = sf.eq_spectrum(
#     name="CPU",
#     Tgas=T,
#     pressure=p,
#     mole_fraction=x,
#     path_length=l,
# )
# s_cpu.apply_slit(w_slit, unit="cm-1")

s_gpu = sf.eq_spectrum_gpu(
    name="GPU",
    Tgas=T,
    pressure=p,
    mole_fraction=x,
    path_length=l,
    backend="gpu-cuda",
)
s_gpu.apply_slit(w_slit, unit="cm-1")
# plot_diff(s_cpu, s_gpu, var="emissivity", wunit="nm", method="diff")
```

```python
In ``C:\Users\Nicolas Minesi\.radisdb\hitemp`` keep only relevant input files:
CO2-02_02125-02250_HITEMP2010.hdf5
CO2-02_02250-02500_HITEMP2010.hdf5
Selected card (deviceID=0):
[X] 0: Intel(R) UHD Graphics
[ ] 1: NVIDIA RTX A1000 Laptop GPU

Traceback (most recent call last):

  File C:\Anaconda\envs\radis-vulkan2\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\nicolas minesi\python\examples\plot_gpu.py:49
    s_gpu = sf.eq_spectrum_gpu(

  File c:\users\nicolas minesi\python\radis\lbl\factory.py:1144 in eq_spectrum_gpu
    gpu_init(

  File c:\users\nicolas minesi\python\radis\gpu\gpu.py:214 in gpu_init
    app.schedule_shader(

  File c:\users\nicolas minesi\python\radis\gpu\vulkan\vulkan_compute_lib.py:84 in schedule_shader
    pipeline, pipelineLayout, computeShaderModule = self.createComputePipeline(

  File c:\users\nicolas minesi\python\radis\gpu\vulkan\vulkan_compute_lib.py:426 in createComputePipeline
    if len(pipelines) == 1:

TypeError: cdata of type 'struct VkPipeline_T *' has no len()
```

I really like the list of available GPU in the prompt btw. I tried with both GPU and it gave the same output.

2023-10-18 11:30 UTC, dcmvdbekerom commented
It looks like the driver wasn't able to load (one of) the shaders (this is what kernels are called in Vulkan). This can happen because Vulkan can use extensions that may or may not be present on your particular device. In the future we can test for this at runtime, but only once we know what the problem is. Which extensions are present depend both on the hardware capabilities as well as the Vulkan version.

My suspicion is that `EXT_scalar_block_layout` is the culprit. To test this, we first need to check your capabilities with the [Vulkan capability viewer](https://www.saschawillems.de/creations/vulkan-hardware-capability-viewer/)

Then can you report back what is the value of `Properties->Core 1.0->apiVersion`? And what is the value of `Features->Core 1.2->scalarBlockLayout`? (this should be True or False). Please check these values for both of your cards (change with "Select device")

2023-10-24 06:15 UTC, minouHub commented
Integrated GPU: Intel(R) UHD Graphics
- apiVersion: 1.3.250
- scalarBlockLayout: true

Integrated GPU: NVIDIA RTX A1000

- apiVersion: 1.3.242
- scalarBlockLayout: true

2023-10-24 19:47 UTC, dcmvdbekerom commented
This all looks good, not sure what's the problem then..

2023-10-27 08:27 UTC, dcmvdbekerom commented
Actually, could you try the most recent version of the PR?
It likely won't solve your issue, but it might point to what's wrong.
I'm hoping it will say `AttributeError: 'GPUApplication' object has no attribute 'applyLineshapes'`, in which case it's a simple path issue.

2023-10-30 08:40 UTC, minouHub commented
same error message after a pull and a `pip install -e .`

2023-10-30 17:39 UTC, minouHub commented
Working with `vulkan==1.1.99.1`

2023-11-02 19:37 UTC, dcmvdbekerom commented
Now also works on linux! Unfortunately not on Travis :(

2023-11-04 16:31 UTC, erwanp commented
@dcmvdbekerom aren't the test failing just because you aren't running on a Travis-GPU enabled instance ? 

It can be activated here: 

https://docs.travis-ci.com/user/reference/overview/#gpu-vm-instance-size

2023-11-05 20:23 UTC, dcmvdbekerom commented
Tests are now working! Still failing for the moment, but at least they are now testing the actual code. The first GPU test is passes, the second (multiple GPU plots) still has issues.

2023-11-14 22:12 UTC, dcmvdbekerom commented
Tests are now passing! This means that the Vulkan driver is working on Linux and tested on the CI server.
As briefly mentioned above, in absence of GPU hardware the Linux Vulkan drivers defaul to a CPU renderer `llvm-pipe`, which is used by Travis to run the GPU tests. 

There was an issue with some erratic output that was produced about ~50% of the time. This was related to not zeroing the buffers before executing the FFT's. Currently the buffers are zeroed _during_ iteration, which may be excessive -- zeroing during initialization might suffice.

2023-11-16 09:23 UTC, minouHub commented
I tried to do a GPU computation with exomol. It failed because the self broadening is not imported correctly. @dcmvdbekerom can you add that to the to-do list. I'll take a look if you want me to

2024-12-16 13:31 UTC, dcmvdbekerom commented
> I tried to do a GPU computation with exomol. It failed because the self broadening is not imported correctly. @dcmvdbekerom can you add that to the to-do list. I'll take a look if you want me to

@minouHub I think I need your help with this!

2024-12-16 17:09 UTC, dcmvdbekerom commented
Reallocate vulkan buffer:

*destroy old buffer*:
vkDestroyBuffer
vkFreeMemory

*allocate new buffer*
vkCreateBuffer
vkAllocateMemory
vkBindBufferMemory

*update references* 
Update Vulkan objects or structure that reference the old buffer (e.g. descriptor sets, bindings)

2025-01-02 17:46 UTC, minouHub commented
> >   I tried to do a GPU computation with exomol. It failed because the self broadening is not imported correctly. @dcmvdbekerom can you add that to the to-do list. I'll take a look if you want me to

> 
> @minouHub I think I need your help with this!

This should be solved when #716 and #720 will be merged!

2025-03-07 17:04 UTC, erwanp commented
Working for me : `plot_gpu_recalc.py`

![image](https://github.com/user-attachments/assets/dae099a2-7659-4f26-b383-038d5fc6c69e)

2025-03-07 17:28 UTC, erwanp requested changes
on frontend side check

- calc_spectrum : https://github.com/radis/radis/blob/develop/radis/lbl/calc.py#L67C1-L67C16
- add argument exit_gpu=False to https://github.com/radis/radis/blob/develop/radis/lbl/calc.py#L958

2025-03-07 17:28 UTC, erwanp commented on radis/gpu/vulkan/shaders/cmdFillLDM.comp
> +    uint iso = floatBitsToUint(database_d[i]); // iterpret data as uint
maybe comment this part ?

2025-03-07 17:28 UTC, erwanp commented on radis/gpu/vulkan/shaders/cmdApplyLineshapes.comp
> +void main() {
comment here too, mention Algorithm

2025-03-07 17:28 UTC, erwanp commented on .travis.yml
> +# <<<<<<< HEAD
pb here

2025-03-07 17:28 UTC, erwanp commented on radis/test/gpu/test_gpu.py
> +##    assert s_list[0].get_power() > 0
```suggestion
```

2025-03-07 17:28 UTC, erwanp commented on radis/lbl/loader.py
> +        "gpu_backend",
check if needed?

2025-03-08 08:45 UTC, dcmvdbekerom commented
We decided to drop support for the CUDA backend, see issue here: https://github.com/radis/radis/issues/758

2025-03-08 11:41 UTC, erwanp requested changes

2025-03-08 11:41 UTC, erwanp commented on radis/lbl/factory.py
> +            Select the Vulkan device. If ``int``, specifies the device index, which is printed when Vulkan is loaded.
```suggestion
            Select the GPU device. If ``int``, specifies the device index, which is printed when Vulkan (the GPU backen d) is loaded.
```

added cleared message because users are not necessarily aware of what Vulkan is

2025-03-09 15:24 UTC, erwanp requested changes

2025-03-09 15:24 UTC, erwanp commented on radis/lbl/calc.py
> +            path_length=path_length,
pressure is missing (note : it as missing before already !?)

2025-03-09 15:52 UTC, dcmvdbekerom commented on radis/lbl/calc.py
> +            path_length=path_length,
Good point, same for non-eq it seems..
I updated it

2025-03-09 19:54 UTC, minouHub commented
From a user perspective, I read the docs, played with the functionality and had fun. No bug. Tried HITRAN, HITEMP, and ExoMol. 
This is however not working for the GEISA database probably because the database does not provide all the columns we expect in the other databases.

2025-03-09 20:06 UTC, dcmvdbekerom reviewed
All changes applied

2025-03-09 20:19 UTC, dcmvdbekerom commented
> From a user perspective, I read the docs, played with the functionality and had fun. No bug. Tried HITRAN, HITEMP, and ExoMol. This is however not working for the GEISA database probably because the database does not provide all the columns we expect in the other databases.

Glad it's (mostly) working! The geisa issue (like the exomol issue before) is not technically a GPU issue so I propose we solve that in a separate PR.

For now, I think it's done so I'll merge it!

2025-03-09 20:19 UTC, merged

2025-03-12 11:25 UTC, erwanp commented on radis/lbl/calc.py
> +            path_length=path_length,
@dcmvdbekerom

2025-03-12 11:30 UTC, dcmvdbekerom commented on radis/lbl/calc.py
> +            path_length=path_length,
It's updated in the development branch: https://github.com/radis/radis/blob/7350e1702cd02b2cde0e993163335e3363bafa7a/radis/lbl/calc.py#L968