re-worked cutoff_error parameter for Automatic linestrength cutoff
radis/radis pull request #646
Opened 2024-03-21 22:16 UTC by code29563

### Description

Addresses issue #268 building on PR #451.

I adjusted some of the docstrings and printed messages to be a bit more informative by clarifying what the function does with the input arguments, i.e. that the user-input `cutoff` is being adjusted to conform to the user-input `cutoff_error`.

I chose to stick to pandas methods for simplicity rather than using numpy. But is compatibility with vaex dataframes also sought in this issue?

2024-03-30 14:30 UTC, minouHub reviewed
Seems good to me but I would like @erwanp feedback. We are also waiting for Travis to be back for automatic tests

2024-04-21 09:59 UTC, erwanp commented
Rebased on latest develop version (with fixed tests), and triggering the test suite to test this PR

2024-04-21 12:02 UTC, erwanp requested changes

2024-04-21 12:02 UTC, erwanp commented on radis/lbl/base.py
> +                if cutoff_error < error:
`error` is not defined and triggers an error

2024-04-21 20:59 UTC, code29563 commented
I've tried fixing the code so it currently supports Pandas DataFrames. What would be the best approach for supporting Vaex, as it doesn't seem to have a `cumsum()` method? Convert to a numpy array then use `numpy.cumsum()`?

2024-04-21 22:09 UTC, erwanp commented
If we convert to Numpy we will loose all the performance benefit of Vaex. We use Vaex when arrays cannot be loaded in RAM. 

There is no straightforward solution. You could try to benchmark a few things on the side; for instance creating a function in radis.misc.arrays to find a cumsum treshold on a >1e10 Vaex array. Make sure that the array doesn't fit in memory, to make sure you are dealing with the worst case scenario. Then; it is probably possible to use vaex to sort and do a bining; and  use Pandas cumsum() the binned array (which will clearly reduce the memory usage). 
This shall be enough to reach less than the user-specified error, without having to load the full array

2024-05-05 09:04 UTC, code29563 commented
I chose 100000 as the limit on length of a df to be processed in memory, which I tested on a dataset with > 3e9 rows, but might be worth testing further.

2024-05-17 16:44 UTC, minouHub commented
Seems good. Could you provide an example that raises a warning?

2024-05-19 19:55 UTC, code29563 commented
> Seems good. Could you provide an example that raises a warning?

For an example that both adjusts the cutoff and raises the `LinestrengthCutoffWarning` (based on example from docs for `eq_spectrum`):
```
from radis import SpectrumFactory
sf = SpectrumFactory(
    wavenum_min=2900,
    wavenum_max=3200,
    molecule="OH",
    wstep='auto',
    cutoff=1e-23
)
sf.misc.warning_linestrength_cutoff = 1e-24
sf.params.cutoff_error = 2
sf.fetch_databank("hitemp")

s1 = sf.eq_spectrum(Tgas=300, path_length=1, pressure=0.1)
```
or set `sf.params.cutoff_error` to >=3.44 for an example without adjusting.

2026-04-19 18:09 UTC, minouHub commented
Closing as a new PR was open (#268). Re-open if interested

2026-04-19 18:09 UTC, closed without merging